//! GENERATED FILE - do not edit by hand.
//! Source: `compiler/libpc300/sc5-in.scp` from alliedmodders/amxmodx (Pawn compiler,
//! Copyright (c) ITB CompuPhase, zlib-style licence - see ATTRIBUTION.md).
//! Regenerate with `node scripts/gendiag.mjs <sc5-in.scp> crates/zpc-diag/src/table.rs`.
//!
//! The texts are reproduced verbatim so that zpc's diagnostics can be compared
//! byte-for-byte against amxxpc's during differential testing.

/// Non-fatal compile errors (codes 1..=99 in the Pawn numbering).
pub static ERRORS: &[(u16, &str)] = &[
    (1, "expected token: \"%s\", but found \"%s\""),
    (2, "only a single statement (or expression) can follow each \"case\""),
    (3, "declaration of a local variable must appear in a compound block"),
    (4, "function \"%s\" is not implemented"),
    (5, "function may not have arguments"),
    (6, "must be assigned to an array"),
    (7, "operator cannot be redefined"),
    (8, "must be a constant expression; assumed zero"),
    (9, "invalid array size (negative or zero)"),
    (10, "invalid function or declaration"),
    (11, "invalid outside functions"),
    (12, "invalid function call, not a valid address"),
    (13, "no entry point (no public functions)"),
    (14, "invalid statement; not in switch"),
    (15, "\"default\" case must be the last case in switch statement"),
    (16, "multiple defaults in \"switch\""),
    (17, "undefined symbol \"%s\""),
    (18, "initialization data exceeds declared size"),
    (19, "not a label: \"%s\""),
    (20, "invalid symbol name \"%s\""),
    (21, "symbol already defined: \"%s\""),
    (22, "must be lvalue (non-constant)"),
    (23, "array assignment must be simple assignment"),
    (24, "\"break\" or \"continue\" is out of context"),
    (25, "function heading differs from prototype"),
    (26, "no matching \"#if...\""),
    (27, "invalid character constant"),
    (28, "invalid subscript (not an array or too many subscripts): \"%s\""),
    (29, "invalid expression, assumed zero"),
    (30, "compound statement not closed at the end of file"),
    (31, "unknown directive"),
    (32, "array index out of bounds (variable \"%s\")"),
    (33, "array must be indexed (variable \"%s\")"),
    (34, "argument does not have a default value (argument %d)"),
    (35, "argument type mismatch (argument %d)"),
    (36, "empty statement"),
    (37, "invalid string (possibly non-terminated string)"),
    (38, "extra characters on line"),
    (39, "constant symbol has no size"),
    (40, "duplicate \"case\" label (value %d)"),
    (41, "invalid ellipsis, array size is not known"),
    (42, "invalid combination of class specifiers"),
    (43, "character constant exceeds range for packed string"),
    (44, "positional parameters must precede all named parameters"),
    (45, "too many function arguments"),
    (46, "unknown array size (variable \"%s\")"),
    (47, "array sizes do not match, or destination array is too small"),
    (48, "array dimensions do not match"),
    (49, "invalid line continuation"),
    (50, "invalid range"),
    (51, "invalid subscript, use \"[ ]\" operators on major dimensions"),
    (52, "multi-dimensional arrays must be fully initialized"),
    (53, "exceeding maximum number of dimensions"),
    (54, "unmatched closing brace"),
    (55, "start of function body without function header"),
    (56, "arrays, local variables and function arguments cannot be public (variable \"%s\")"),
    (57, "unfinished expression before compiler directive"),
    (58, "duplicate argument; same argument is passed twice"),
    (59, "function argument may not have a default value (variable \"%s\")"),
    (60, "multiple \"#else\" directives between \"#if ... #endif\""),
    (61, "\"#elseif\" directive follows an \"#else\" directive"),
    (62, "number of operands does not fit the operator"),
    (63, "function result tag of operator \"%s\" must be \"%s\""),
    (64, "cannot change predefined operators"),
    (65, "function argument may only have a single tag (argument %d)"),
    (66, "function argument may not be a reference argument or an array (argument \"%s\")"),
    (67, "variable cannot be both a reference and an array (variable \"%s\")"),
    (68, "invalid rational number precision in #pragma"),
    (69, "rational number format already defined"),
    (70, "rational number support was not enabled"),
    (71, "user-defined operator must be declared before use (function \"%s\")"),
    (72, "\"sizeof\" operator is invalid on \"function\" symbols"),
    (73, "function argument must be an array (argument \"%s\")"),
    (74, "#define pattern must start with an alphabetic character"),
    (75, "input line too long (after substitutions)"),
    (76, "syntax error in the expression, or invalid function call"),
    (77, "malformed UTF-8 encoding, or corrupted file: %s"),
    (78, "function uses both \"return\" and \"return <value>\""),
    (79, "inconsistent return types (array & non-array)"),
    (80, "unknown symbol, or not a constant symbol (symbol \"%s\")"),
    (81, "cannot take a tag as a default value for an indexed array parameter (symbol \"%s\")"),
    (82, "user-defined operators and native functions may not have states"),
    (83, "a function may only belong to a single automaton (symbol \"%s\")"),
    (84, "state conflict: one of the states is already assigned to another implementation (symbol \"%s\")"),
    (85, "no states are defined for function \"%s\""),
    (86, "unknown automaton \"%s\""),
    (87, "unknown state \"%s\" for automaton \"%s\""),
    (88, "number of arguments does not match definition"),
];

/// Fatal errors that abort the compile (codes 100..=199).
pub static FATALS: &[(u16, &str)] = &[
    (100, "cannot read from file: \"%s\""),
    (101, "cannot write to file: \"%s\""),
    (102, "table overflow: \"%s\""),
    (103, "insufficient memory"),
    (104, "invalid assembler instruction \"%s\""),
    (105, "numeric overflow, exceeding capacity"),
    (106, "compiled script exceeds the maximum memory size (%ld bytes)"),
    (107, "too many error messages on one line"),
    (108, "codepage mapping file not found"),
    (109, "invalid path: \"%s\""),
    (110, "assertion failed: %s"),
    (111, "user error: %s"),
    (112, "specify either all dimensions or only the last dimension"),
];

/// Warnings (codes 200..=234; amxxpc defines no code above 234).
pub static WARNINGS: &[(u16, &str)] = &[
    (200, "symbol \"%s\" is truncated to %d characters"),
    (201, "redefinition of constant/macro (symbol \"%s\")"),
    (202, "number of arguments does not match definition"),
    (203, "symbol is never used: \"%s\""),
    (204, "symbol is assigned a value that is never used: \"%s\""),
    (205, "redundant code: constant expression is zero"),
    (206, "redundant test: constant expression is non-zero"),
    (207, "unknown #pragma"),
    (208, "function with tag result used before definition, forcing reparse"),
    (209, "function \"%s\" should return a value"),
    (210, "possible use of symbol before initialization: \"%s\""),
    (211, "possibly unintended assignment"),
    (212, "possibly unintended bitwise operation"),
    (213, "tag mismatch"),
    (214, "possibly a \"const\" array argument was intended: \"%s\""),
    (215, "expression has no effect"),
    (216, "nested comment"),
    (217, "loose indentation"),
    (218, "old style prototypes used with optional semicolumns"),
    (219, "local variable \"%s\" shadows a variable at a preceding level"),
    (220, "expression with tag override must appear between parentheses"),
    (221, "label name \"%s\" shadows tag name"),
    (222, "number of digits exceeds rational number precision"),
    (223, "redundant \"sizeof\": argument size is always 1 (symbol \"%s\")"),
    (224, "indeterminate array size in \"sizeof\" expression (symbol \"%s\")"),
    (225, "unreachable code"),
    (226, "a variable is assigned to itself (symbol \"%s\")"),
    (227, "more initiallers than enum fields"),
    (228, "length of initialler exceeds size of the enum field"),
    (229, "index tag mismatch (symbol \"%s\")"),
    (230, "no implementation for state \"%s\" / function \"%s\", no fall-back"),
    (231, "state specification on forward declaration is ignored"),
    (232, "output file is written, but with compact encoding disabled"),
    (233, "symbol \"%s\" is marked as deprecated: %s"),
    (234, "recursive function \"%s\""),
];

/// Look up the message template for a diagnostic code.
pub fn message(code: u16) -> Option<&'static str> {
    let table = match code {
        0..=99 => ERRORS,
        100..=199 => FATALS,
        _ => WARNINGS,
    };
    table.iter().find(|(c, _)| *c == code).map(|(_, m)| *m)
}
