//! The AMX instruction set: opcode numbers, mnemonics and operand encoding.
//!
//! GENERATED by `scripts/genopcodes.mjs` from the AMX Mod X compiler's
//! `libpc300/sc6.c` `opcodelist[]` table - do not edit by hand.
//!
//! The numbers here are a binary format: the assembler writes them straight into
//! the `.amx` code segment, so a wrong value produces a plugin that misbehaves at
//! runtime rather than failing to compile. `sc6.c` is the authoritative source in
//! this tree; the copy of `amx.h` shipped with `libpc300` declares only the runtime
//! structures and does not contain the `OP_*` enum.
//!
//! Operand counts come from the emit function each row is bound to in `sc6.c`:
//! `parm0` writes the opcode alone, `parm1` writes one operand cell, `parm2` two,
//! and `do_call` / `do_jump` / `do_switch` each write one operand cell holding a
//! resolved code address (`lbltab[i]`). `casetbl` is declared `parm0` but is
//! followed by a variable-length table written by `do_case` - see [`Operands`].

/// How many cell-sized operands follow an opcode in the code segment.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Operands {
    /// No operands: the instruction is a single cell (sc6.c `parm0`).
    None,
    /// One operand cell (sc6.c `parm1`, `do_call`, `do_jump`, `do_switch`).
    One,
    /// Two operand cells (sc6.c `parm2`; debug records only).
    Two,
    /// [`Opcode::Casetbl`]: the opcode is followed by `2 + 2 * n` cells. sc6.c emits
    /// these as `case` rows through `do_case`, which writes two cells and *no*
    /// opcode. The first pair is `(n, default_address)`, the remaining `n` pairs are
    /// `(match_value, code_address)`. Every address in the table needs relocation.
    CaseTable,
    /// Variable length, encoded by the instruction itself (sc6.c `do_file` /
    /// `do_symbol`: a size cell followed by an inline string). Never emitted by
    /// this compiler - both rows are commented out of `opcodelist`.
    Variable,
}

impl Operands {
    /// The number of operand cells, when it is fixed. `None` for the
    /// variable-length forms, whose size can only be known from the bytecode.
    pub fn count(self) -> Option<u32> {
        match self {
            Operands::None => Some(0),
            Operands::One => Some(1),
            Operands::Two => Some(2),
            Operands::CaseTable | Operands::Variable => Option::None,
        }
    }
}

/// An AMX instruction. Discriminants are the on-disk opcode numbers.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[repr(u8)]
pub enum Opcode {
    /// Not an instruction. sc6.c reserves entry 0 of `opcodelist` as the
    /// "invalid instruction" node; the mnemonic `none` is our own placeholder so that
    /// every variant round-trips through [`Opcode::mnemonic`].
    None = 0,
    /// PRI = [address]
    LoadPri = 1,
    /// ALT = [address]
    LoadAlt = 2,
    /// PRI = [FRM + offset]
    LoadSPri = 3,
    /// ALT = [FRM + offset]
    LoadSAlt = 4,
    /// PRI = [[address]]
    LrefPri = 5,
    /// ALT = [[address]]
    LrefAlt = 6,
    /// PRI = [[FRM + offset]]
    LrefSPri = 7,
    /// ALT = [[FRM + offset]]
    LrefSAlt = 8,
    /// PRI = [PRI]
    LoadI = 9,
    /// PRI = "number" bytes from [PRI] (partial cell load)
    LodbI = 10,
    /// PRI = value
    ConstPri = 11,
    /// ALT = value
    ConstAlt = 12,
    /// PRI = FRM + offset
    AddrPri = 13,
    /// ALT = FRM + offset
    AddrAlt = 14,
    /// [address] = PRI
    StorPri = 15,
    /// [address] = ALT
    StorAlt = 16,
    StorSPri = 17,
    StorSAlt = 18,
    SrefPri = 19,
    SrefAlt = 20,
    SrefSPri = 21,
    SrefSAlt = 22,
    /// [ALT] = PRI
    StorI = 23,
    /// store "number" bytes of PRI at [ALT]
    StrbI = 24,
    /// PRI = [ALT + (PRI x cell size)]
    Lidx = 25,
    /// PRI = [ALT + (PRI << shift)]
    LidxB = 26,
    /// PRI = ALT + (PRI x cell size)
    Idxaddr = 27,
    /// PRI = ALT + (PRI << shift)
    IdxaddrB = 28,
    /// align PRI for a packed-string access of "number" bytes
    AlignPri = 29,
    AlignAlt = 30,
    /// PRI = special register (COD/DAT/HEA/STP/STK/FRM/CIP)
    Lctrl = 31,
    /// special register = PRI
    Sctrl = 32,
    MovePri = 33,
    MoveAlt = 34,
    Xchg = 35,
    PushPri = 36,
    PushAlt = 37,
    /// push a reference: the value at [value] relative to DAT, "value" times
    PushR = 38,
    PushC = 39,
    Push = 40,
    PushS = 41,
    PopPri = 42,
    PopAlt = 43,
    /// ALT = STK, STK = STK + value (adjust the stack)
    Stack = 44,
    /// ALT = HEA, HEA = HEA + value (allocate on the heap)
    Heap = 45,
    /// function prologue: push FRM, FRM = STK
    Proc = 46,
    /// function epilogue without stack cleanup
    Ret = 47,
    /// function epilogue: pop FRM and the argument count
    Retn = 48,
    /// call a function; the operand is a code address
    Call = 49,
    CallPri = 50,
    /// unconditional jump; the operand is a code address
    Jump = 51,
    /// jump relative to the current CIP by a plain number (not a label)
    Jrel = 52,
    Jzer = 53,
    Jnz = 54,
    Jeq = 55,
    Jneq = 56,
    Jless = 57,
    Jleq = 58,
    Jgrtr = 59,
    Jgeq = 60,
    Jsless = 61,
    Jsleq = 62,
    Jsgrtr = 63,
    Jsgeq = 64,
    Shl = 65,
    Shr = 66,
    Sshr = 67,
    ShlCPri = 68,
    ShlCAlt = 69,
    ShrCPri = 70,
    ShrCAlt = 71,
    Smul = 72,
    Sdiv = 73,
    SdivAlt = 74,
    Umul = 75,
    Udiv = 76,
    UdivAlt = 77,
    Add = 78,
    Sub = 79,
    SubAlt = 80,
    And = 81,
    Or = 82,
    Xor = 83,
    Not = 84,
    Neg = 85,
    Invert = 86,
    AddC = 87,
    SmulC = 88,
    ZeroPri = 89,
    ZeroAlt = 90,
    Zero = 91,
    ZeroS = 92,
    SignPri = 93,
    SignAlt = 94,
    Eq = 95,
    Neq = 96,
    Less = 97,
    Leq = 98,
    Grtr = 99,
    Geq = 100,
    Sless = 101,
    Sleq = 102,
    Sgrtr = 103,
    Sgeq = 104,
    EqCPri = 105,
    EqCAlt = 106,
    IncPri = 107,
    IncAlt = 108,
    Inc = 109,
    IncS = 110,
    IncI = 111,
    DecPri = 112,
    DecAlt = 113,
    Dec = 114,
    DecS = 115,
    DecI = 116,
    Movs = 117,
    Cmps = 118,
    Fill = 119,
    /// abort execution with the given exit code
    Halt = 120,
    /// abort with an array-bounds error if PRI > value
    Bounds = 121,
    /// call the native function whose index is in PRI
    SysreqPri = 122,
    /// call the native function with the given index (arguments already pushed)
    SysreqC = 123,
    /// Debug record: source file name. Variable length (the string follows).
    /// Commented out of sc6.c's table - never emitted by this compiler.
    File = 124,
    /// Debug record: line number. Commented out of sc6.c's table.
    Line = 125,
    /// Debug record: symbol name. Variable length. Commented out of sc6.c's table.
    Symbol = 126,
    /// Debug record: symbol range. Commented out of sc6.c's table.
    Srange = 127,
    /// jump to the code address in PRI
    JumpPri = 128,
    /// switch: the operand is the code address of the following CASETBL
    Switch = 129,
    /// case table header; followed by a variable-length list of (value, address) pairs
    Casetbl = 130,
    SwapPri = 131,
    SwapAlt = 132,
    /// push the address of a local (FRM + offset)
    Pushaddr = 133,
    /// no operation (padding)
    Nop = 134,
    /// call a native by its direct address; not generated by this compiler
    SysreqD = 135,
    /// Debug record: symbol tag. Commented out of sc6.c's table.
    Symtag = 136,
    /// debugger breakpoint
    Break = 137,
}

/// Every opcode, in ascending numeric order.
pub const ALL: [Opcode; 138] = [
    Opcode::None,
    Opcode::LoadPri,
    Opcode::LoadAlt,
    Opcode::LoadSPri,
    Opcode::LoadSAlt,
    Opcode::LrefPri,
    Opcode::LrefAlt,
    Opcode::LrefSPri,
    Opcode::LrefSAlt,
    Opcode::LoadI,
    Opcode::LodbI,
    Opcode::ConstPri,
    Opcode::ConstAlt,
    Opcode::AddrPri,
    Opcode::AddrAlt,
    Opcode::StorPri,
    Opcode::StorAlt,
    Opcode::StorSPri,
    Opcode::StorSAlt,
    Opcode::SrefPri,
    Opcode::SrefAlt,
    Opcode::SrefSPri,
    Opcode::SrefSAlt,
    Opcode::StorI,
    Opcode::StrbI,
    Opcode::Lidx,
    Opcode::LidxB,
    Opcode::Idxaddr,
    Opcode::IdxaddrB,
    Opcode::AlignPri,
    Opcode::AlignAlt,
    Opcode::Lctrl,
    Opcode::Sctrl,
    Opcode::MovePri,
    Opcode::MoveAlt,
    Opcode::Xchg,
    Opcode::PushPri,
    Opcode::PushAlt,
    Opcode::PushR,
    Opcode::PushC,
    Opcode::Push,
    Opcode::PushS,
    Opcode::PopPri,
    Opcode::PopAlt,
    Opcode::Stack,
    Opcode::Heap,
    Opcode::Proc,
    Opcode::Ret,
    Opcode::Retn,
    Opcode::Call,
    Opcode::CallPri,
    Opcode::Jump,
    Opcode::Jrel,
    Opcode::Jzer,
    Opcode::Jnz,
    Opcode::Jeq,
    Opcode::Jneq,
    Opcode::Jless,
    Opcode::Jleq,
    Opcode::Jgrtr,
    Opcode::Jgeq,
    Opcode::Jsless,
    Opcode::Jsleq,
    Opcode::Jsgrtr,
    Opcode::Jsgeq,
    Opcode::Shl,
    Opcode::Shr,
    Opcode::Sshr,
    Opcode::ShlCPri,
    Opcode::ShlCAlt,
    Opcode::ShrCPri,
    Opcode::ShrCAlt,
    Opcode::Smul,
    Opcode::Sdiv,
    Opcode::SdivAlt,
    Opcode::Umul,
    Opcode::Udiv,
    Opcode::UdivAlt,
    Opcode::Add,
    Opcode::Sub,
    Opcode::SubAlt,
    Opcode::And,
    Opcode::Or,
    Opcode::Xor,
    Opcode::Not,
    Opcode::Neg,
    Opcode::Invert,
    Opcode::AddC,
    Opcode::SmulC,
    Opcode::ZeroPri,
    Opcode::ZeroAlt,
    Opcode::Zero,
    Opcode::ZeroS,
    Opcode::SignPri,
    Opcode::SignAlt,
    Opcode::Eq,
    Opcode::Neq,
    Opcode::Less,
    Opcode::Leq,
    Opcode::Grtr,
    Opcode::Geq,
    Opcode::Sless,
    Opcode::Sleq,
    Opcode::Sgrtr,
    Opcode::Sgeq,
    Opcode::EqCPri,
    Opcode::EqCAlt,
    Opcode::IncPri,
    Opcode::IncAlt,
    Opcode::Inc,
    Opcode::IncS,
    Opcode::IncI,
    Opcode::DecPri,
    Opcode::DecAlt,
    Opcode::Dec,
    Opcode::DecS,
    Opcode::DecI,
    Opcode::Movs,
    Opcode::Cmps,
    Opcode::Fill,
    Opcode::Halt,
    Opcode::Bounds,
    Opcode::SysreqPri,
    Opcode::SysreqC,
    Opcode::File,
    Opcode::Line,
    Opcode::Symbol,
    Opcode::Srange,
    Opcode::JumpPri,
    Opcode::Switch,
    Opcode::Casetbl,
    Opcode::SwapPri,
    Opcode::SwapAlt,
    Opcode::Pushaddr,
    Opcode::Nop,
    Opcode::SysreqD,
    Opcode::Symtag,
    Opcode::Break,
];

impl Opcode {
    /// The mnemonic as `sc6.c`'s `opcodelist[]` spells it.
    pub fn mnemonic(self) -> &'static str {
        match self {
            Opcode::None => "none",
            Opcode::LoadPri => "load.pri",
            Opcode::LoadAlt => "load.alt",
            Opcode::LoadSPri => "load.s.pri",
            Opcode::LoadSAlt => "load.s.alt",
            Opcode::LrefPri => "lref.pri",
            Opcode::LrefAlt => "lref.alt",
            Opcode::LrefSPri => "lref.s.pri",
            Opcode::LrefSAlt => "lref.s.alt",
            Opcode::LoadI => "load.i",
            Opcode::LodbI => "lodb.i",
            Opcode::ConstPri => "const.pri",
            Opcode::ConstAlt => "const.alt",
            Opcode::AddrPri => "addr.pri",
            Opcode::AddrAlt => "addr.alt",
            Opcode::StorPri => "stor.pri",
            Opcode::StorAlt => "stor.alt",
            Opcode::StorSPri => "stor.s.pri",
            Opcode::StorSAlt => "stor.s.alt",
            Opcode::SrefPri => "sref.pri",
            Opcode::SrefAlt => "sref.alt",
            Opcode::SrefSPri => "sref.s.pri",
            Opcode::SrefSAlt => "sref.s.alt",
            Opcode::StorI => "stor.i",
            Opcode::StrbI => "strb.i",
            Opcode::Lidx => "lidx",
            Opcode::LidxB => "lidx.b",
            Opcode::Idxaddr => "idxaddr",
            Opcode::IdxaddrB => "idxaddr.b",
            Opcode::AlignPri => "align.pri",
            Opcode::AlignAlt => "align.alt",
            Opcode::Lctrl => "lctrl",
            Opcode::Sctrl => "sctrl",
            Opcode::MovePri => "move.pri",
            Opcode::MoveAlt => "move.alt",
            Opcode::Xchg => "xchg",
            Opcode::PushPri => "push.pri",
            Opcode::PushAlt => "push.alt",
            Opcode::PushR => "push.r",
            Opcode::PushC => "push.c",
            Opcode::Push => "push",
            Opcode::PushS => "push.s",
            Opcode::PopPri => "pop.pri",
            Opcode::PopAlt => "pop.alt",
            Opcode::Stack => "stack",
            Opcode::Heap => "heap",
            Opcode::Proc => "proc",
            Opcode::Ret => "ret",
            Opcode::Retn => "retn",
            Opcode::Call => "call",
            Opcode::CallPri => "call.pri",
            Opcode::Jump => "jump",
            Opcode::Jrel => "jrel",
            Opcode::Jzer => "jzer",
            Opcode::Jnz => "jnz",
            Opcode::Jeq => "jeq",
            Opcode::Jneq => "jneq",
            Opcode::Jless => "jless",
            Opcode::Jleq => "jleq",
            Opcode::Jgrtr => "jgrtr",
            Opcode::Jgeq => "jgeq",
            Opcode::Jsless => "jsless",
            Opcode::Jsleq => "jsleq",
            Opcode::Jsgrtr => "jsgrtr",
            Opcode::Jsgeq => "jsgeq",
            Opcode::Shl => "shl",
            Opcode::Shr => "shr",
            Opcode::Sshr => "sshr",
            Opcode::ShlCPri => "shl.c.pri",
            Opcode::ShlCAlt => "shl.c.alt",
            Opcode::ShrCPri => "shr.c.pri",
            Opcode::ShrCAlt => "shr.c.alt",
            Opcode::Smul => "smul",
            Opcode::Sdiv => "sdiv",
            Opcode::SdivAlt => "sdiv.alt",
            Opcode::Umul => "umul",
            Opcode::Udiv => "udiv",
            Opcode::UdivAlt => "udiv.alt",
            Opcode::Add => "add",
            Opcode::Sub => "sub",
            Opcode::SubAlt => "sub.alt",
            Opcode::And => "and",
            Opcode::Or => "or",
            Opcode::Xor => "xor",
            Opcode::Not => "not",
            Opcode::Neg => "neg",
            Opcode::Invert => "invert",
            Opcode::AddC => "add.c",
            Opcode::SmulC => "smul.c",
            Opcode::ZeroPri => "zero.pri",
            Opcode::ZeroAlt => "zero.alt",
            Opcode::Zero => "zero",
            Opcode::ZeroS => "zero.s",
            Opcode::SignPri => "sign.pri",
            Opcode::SignAlt => "sign.alt",
            Opcode::Eq => "eq",
            Opcode::Neq => "neq",
            Opcode::Less => "less",
            Opcode::Leq => "leq",
            Opcode::Grtr => "grtr",
            Opcode::Geq => "geq",
            Opcode::Sless => "sless",
            Opcode::Sleq => "sleq",
            Opcode::Sgrtr => "sgrtr",
            Opcode::Sgeq => "sgeq",
            Opcode::EqCPri => "eq.c.pri",
            Opcode::EqCAlt => "eq.c.alt",
            Opcode::IncPri => "inc.pri",
            Opcode::IncAlt => "inc.alt",
            Opcode::Inc => "inc",
            Opcode::IncS => "inc.s",
            Opcode::IncI => "inc.i",
            Opcode::DecPri => "dec.pri",
            Opcode::DecAlt => "dec.alt",
            Opcode::Dec => "dec",
            Opcode::DecS => "dec.s",
            Opcode::DecI => "dec.i",
            Opcode::Movs => "movs",
            Opcode::Cmps => "cmps",
            Opcode::Fill => "fill",
            Opcode::Halt => "halt",
            Opcode::Bounds => "bounds",
            Opcode::SysreqPri => "sysreq.pri",
            Opcode::SysreqC => "sysreq.c",
            Opcode::File => "file",
            Opcode::Line => "line",
            Opcode::Symbol => "symbol",
            Opcode::Srange => "srange",
            Opcode::JumpPri => "jump.pri",
            Opcode::Switch => "switch",
            Opcode::Casetbl => "casetbl",
            Opcode::SwapPri => "swap.pri",
            Opcode::SwapAlt => "swap.alt",
            Opcode::Pushaddr => "pushaddr",
            Opcode::Nop => "nop",
            Opcode::SysreqD => "sysreq.d",
            Opcode::Symtag => "symtag",
            Opcode::Break => "break",
        }
    }

    /// Look up an opcode by mnemonic. Case-sensitive: the compiler emits
    /// lower-case mnemonics, and `sc6.c`'s `findopcode` binary-searches this exact
    /// spelling.
    pub fn from_mnemonic(name: &str) -> Option<Opcode> {
        Some(match name {
            "none" => Opcode::None,
            "load.pri" => Opcode::LoadPri,
            "load.alt" => Opcode::LoadAlt,
            "load.s.pri" => Opcode::LoadSPri,
            "load.s.alt" => Opcode::LoadSAlt,
            "lref.pri" => Opcode::LrefPri,
            "lref.alt" => Opcode::LrefAlt,
            "lref.s.pri" => Opcode::LrefSPri,
            "lref.s.alt" => Opcode::LrefSAlt,
            "load.i" => Opcode::LoadI,
            "lodb.i" => Opcode::LodbI,
            "const.pri" => Opcode::ConstPri,
            "const.alt" => Opcode::ConstAlt,
            "addr.pri" => Opcode::AddrPri,
            "addr.alt" => Opcode::AddrAlt,
            "stor.pri" => Opcode::StorPri,
            "stor.alt" => Opcode::StorAlt,
            "stor.s.pri" => Opcode::StorSPri,
            "stor.s.alt" => Opcode::StorSAlt,
            "sref.pri" => Opcode::SrefPri,
            "sref.alt" => Opcode::SrefAlt,
            "sref.s.pri" => Opcode::SrefSPri,
            "sref.s.alt" => Opcode::SrefSAlt,
            "stor.i" => Opcode::StorI,
            "strb.i" => Opcode::StrbI,
            "lidx" => Opcode::Lidx,
            "lidx.b" => Opcode::LidxB,
            "idxaddr" => Opcode::Idxaddr,
            "idxaddr.b" => Opcode::IdxaddrB,
            "align.pri" => Opcode::AlignPri,
            "align.alt" => Opcode::AlignAlt,
            "lctrl" => Opcode::Lctrl,
            "sctrl" => Opcode::Sctrl,
            "move.pri" => Opcode::MovePri,
            "move.alt" => Opcode::MoveAlt,
            "xchg" => Opcode::Xchg,
            "push.pri" => Opcode::PushPri,
            "push.alt" => Opcode::PushAlt,
            "push.r" => Opcode::PushR,
            "push.c" => Opcode::PushC,
            "push" => Opcode::Push,
            "push.s" => Opcode::PushS,
            "pop.pri" => Opcode::PopPri,
            "pop.alt" => Opcode::PopAlt,
            "stack" => Opcode::Stack,
            "heap" => Opcode::Heap,
            "proc" => Opcode::Proc,
            "ret" => Opcode::Ret,
            "retn" => Opcode::Retn,
            "call" => Opcode::Call,
            "call.pri" => Opcode::CallPri,
            "jump" => Opcode::Jump,
            "jrel" => Opcode::Jrel,
            "jzer" => Opcode::Jzer,
            "jnz" => Opcode::Jnz,
            "jeq" => Opcode::Jeq,
            "jneq" => Opcode::Jneq,
            "jless" => Opcode::Jless,
            "jleq" => Opcode::Jleq,
            "jgrtr" => Opcode::Jgrtr,
            "jgeq" => Opcode::Jgeq,
            "jsless" => Opcode::Jsless,
            "jsleq" => Opcode::Jsleq,
            "jsgrtr" => Opcode::Jsgrtr,
            "jsgeq" => Opcode::Jsgeq,
            "shl" => Opcode::Shl,
            "shr" => Opcode::Shr,
            "sshr" => Opcode::Sshr,
            "shl.c.pri" => Opcode::ShlCPri,
            "shl.c.alt" => Opcode::ShlCAlt,
            "shr.c.pri" => Opcode::ShrCPri,
            "shr.c.alt" => Opcode::ShrCAlt,
            "smul" => Opcode::Smul,
            "sdiv" => Opcode::Sdiv,
            "sdiv.alt" => Opcode::SdivAlt,
            "umul" => Opcode::Umul,
            "udiv" => Opcode::Udiv,
            "udiv.alt" => Opcode::UdivAlt,
            "add" => Opcode::Add,
            "sub" => Opcode::Sub,
            "sub.alt" => Opcode::SubAlt,
            "and" => Opcode::And,
            "or" => Opcode::Or,
            "xor" => Opcode::Xor,
            "not" => Opcode::Not,
            "neg" => Opcode::Neg,
            "invert" => Opcode::Invert,
            "add.c" => Opcode::AddC,
            "smul.c" => Opcode::SmulC,
            "zero.pri" => Opcode::ZeroPri,
            "zero.alt" => Opcode::ZeroAlt,
            "zero" => Opcode::Zero,
            "zero.s" => Opcode::ZeroS,
            "sign.pri" => Opcode::SignPri,
            "sign.alt" => Opcode::SignAlt,
            "eq" => Opcode::Eq,
            "neq" => Opcode::Neq,
            "less" => Opcode::Less,
            "leq" => Opcode::Leq,
            "grtr" => Opcode::Grtr,
            "geq" => Opcode::Geq,
            "sless" => Opcode::Sless,
            "sleq" => Opcode::Sleq,
            "sgrtr" => Opcode::Sgrtr,
            "sgeq" => Opcode::Sgeq,
            "eq.c.pri" => Opcode::EqCPri,
            "eq.c.alt" => Opcode::EqCAlt,
            "inc.pri" => Opcode::IncPri,
            "inc.alt" => Opcode::IncAlt,
            "inc" => Opcode::Inc,
            "inc.s" => Opcode::IncS,
            "inc.i" => Opcode::IncI,
            "dec.pri" => Opcode::DecPri,
            "dec.alt" => Opcode::DecAlt,
            "dec" => Opcode::Dec,
            "dec.s" => Opcode::DecS,
            "dec.i" => Opcode::DecI,
            "movs" => Opcode::Movs,
            "cmps" => Opcode::Cmps,
            "fill" => Opcode::Fill,
            "halt" => Opcode::Halt,
            "bounds" => Opcode::Bounds,
            "sysreq.pri" => Opcode::SysreqPri,
            "sysreq.c" => Opcode::SysreqC,
            "file" => Opcode::File,
            "line" => Opcode::Line,
            "symbol" => Opcode::Symbol,
            "srange" => Opcode::Srange,
            "jump.pri" => Opcode::JumpPri,
            "switch" => Opcode::Switch,
            "casetbl" => Opcode::Casetbl,
            "swap.pri" => Opcode::SwapPri,
            "swap.alt" => Opcode::SwapAlt,
            "pushaddr" => Opcode::Pushaddr,
            "nop" => Opcode::Nop,
            "sysreq.d" => Opcode::SysreqD,
            "symtag" => Opcode::Symtag,
            "break" => Opcode::Break,
            _ => return Option::None,
        })
    }

    /// The opcode's numeric value, as written to the code segment.
    pub fn raw(self) -> u8 {
        self as u8
    }

    /// Decode a numeric opcode read back from bytecode.
    pub fn from_raw(raw: u8) -> Option<Opcode> {
        ALL.get(raw as usize).copied()
    }

    /// How many operand cells follow this opcode.
    pub fn operands(self) -> Operands {
        match self {
            Opcode::None => Operands::None,
            Opcode::LoadPri => Operands::One,
            Opcode::LoadAlt => Operands::One,
            Opcode::LoadSPri => Operands::One,
            Opcode::LoadSAlt => Operands::One,
            Opcode::LrefPri => Operands::One,
            Opcode::LrefAlt => Operands::One,
            Opcode::LrefSPri => Operands::One,
            Opcode::LrefSAlt => Operands::One,
            Opcode::LoadI => Operands::None,
            Opcode::LodbI => Operands::One,
            Opcode::ConstPri => Operands::One,
            Opcode::ConstAlt => Operands::One,
            Opcode::AddrPri => Operands::One,
            Opcode::AddrAlt => Operands::One,
            Opcode::StorPri => Operands::One,
            Opcode::StorAlt => Operands::One,
            Opcode::StorSPri => Operands::One,
            Opcode::StorSAlt => Operands::One,
            Opcode::SrefPri => Operands::One,
            Opcode::SrefAlt => Operands::One,
            Opcode::SrefSPri => Operands::One,
            Opcode::SrefSAlt => Operands::One,
            Opcode::StorI => Operands::None,
            Opcode::StrbI => Operands::One,
            Opcode::Lidx => Operands::None,
            Opcode::LidxB => Operands::One,
            Opcode::Idxaddr => Operands::None,
            Opcode::IdxaddrB => Operands::One,
            Opcode::AlignPri => Operands::One,
            Opcode::AlignAlt => Operands::One,
            Opcode::Lctrl => Operands::One,
            Opcode::Sctrl => Operands::One,
            Opcode::MovePri => Operands::None,
            Opcode::MoveAlt => Operands::None,
            Opcode::Xchg => Operands::None,
            Opcode::PushPri => Operands::None,
            Opcode::PushAlt => Operands::None,
            Opcode::PushR => Operands::One,
            Opcode::PushC => Operands::One,
            Opcode::Push => Operands::One,
            Opcode::PushS => Operands::One,
            Opcode::PopPri => Operands::None,
            Opcode::PopAlt => Operands::None,
            Opcode::Stack => Operands::One,
            Opcode::Heap => Operands::One,
            Opcode::Proc => Operands::None,
            Opcode::Ret => Operands::None,
            Opcode::Retn => Operands::None,
            Opcode::Call => Operands::One,
            Opcode::CallPri => Operands::None,
            Opcode::Jump => Operands::One,
            Opcode::Jrel => Operands::One,
            Opcode::Jzer => Operands::One,
            Opcode::Jnz => Operands::One,
            Opcode::Jeq => Operands::One,
            Opcode::Jneq => Operands::One,
            Opcode::Jless => Operands::One,
            Opcode::Jleq => Operands::One,
            Opcode::Jgrtr => Operands::One,
            Opcode::Jgeq => Operands::One,
            Opcode::Jsless => Operands::One,
            Opcode::Jsleq => Operands::One,
            Opcode::Jsgrtr => Operands::One,
            Opcode::Jsgeq => Operands::One,
            Opcode::Shl => Operands::None,
            Opcode::Shr => Operands::None,
            Opcode::Sshr => Operands::None,
            Opcode::ShlCPri => Operands::One,
            Opcode::ShlCAlt => Operands::One,
            Opcode::ShrCPri => Operands::One,
            Opcode::ShrCAlt => Operands::One,
            Opcode::Smul => Operands::None,
            Opcode::Sdiv => Operands::None,
            Opcode::SdivAlt => Operands::None,
            Opcode::Umul => Operands::None,
            Opcode::Udiv => Operands::None,
            Opcode::UdivAlt => Operands::None,
            Opcode::Add => Operands::None,
            Opcode::Sub => Operands::None,
            Opcode::SubAlt => Operands::None,
            Opcode::And => Operands::None,
            Opcode::Or => Operands::None,
            Opcode::Xor => Operands::None,
            Opcode::Not => Operands::None,
            Opcode::Neg => Operands::None,
            Opcode::Invert => Operands::None,
            Opcode::AddC => Operands::One,
            Opcode::SmulC => Operands::One,
            Opcode::ZeroPri => Operands::None,
            Opcode::ZeroAlt => Operands::None,
            Opcode::Zero => Operands::One,
            Opcode::ZeroS => Operands::One,
            Opcode::SignPri => Operands::None,
            Opcode::SignAlt => Operands::None,
            Opcode::Eq => Operands::None,
            Opcode::Neq => Operands::None,
            Opcode::Less => Operands::None,
            Opcode::Leq => Operands::None,
            Opcode::Grtr => Operands::None,
            Opcode::Geq => Operands::None,
            Opcode::Sless => Operands::None,
            Opcode::Sleq => Operands::None,
            Opcode::Sgrtr => Operands::None,
            Opcode::Sgeq => Operands::None,
            Opcode::EqCPri => Operands::One,
            Opcode::EqCAlt => Operands::One,
            Opcode::IncPri => Operands::None,
            Opcode::IncAlt => Operands::None,
            Opcode::Inc => Operands::One,
            Opcode::IncS => Operands::One,
            Opcode::IncI => Operands::None,
            Opcode::DecPri => Operands::None,
            Opcode::DecAlt => Operands::None,
            Opcode::Dec => Operands::One,
            Opcode::DecS => Operands::One,
            Opcode::DecI => Operands::None,
            Opcode::Movs => Operands::One,
            Opcode::Cmps => Operands::One,
            Opcode::Fill => Operands::One,
            Opcode::Halt => Operands::One,
            Opcode::Bounds => Operands::One,
            Opcode::SysreqPri => Operands::None,
            Opcode::SysreqC => Operands::One,
            Opcode::File => Operands::Variable,
            Opcode::Line => Operands::Two,
            Opcode::Symbol => Operands::Variable,
            Opcode::Srange => Operands::Two,
            Opcode::JumpPri => Operands::None,
            Opcode::Switch => Operands::One,
            Opcode::Casetbl => Operands::CaseTable,
            Opcode::SwapPri => Operands::None,
            Opcode::SwapAlt => Operands::None,
            Opcode::Pushaddr => Operands::One,
            Opcode::Nop => Operands::None,
            Opcode::SysreqD => Operands::One,
            Opcode::Symtag => Operands::One,
            Opcode::Break => Operands::None,
        }
    }

    /// True when the single operand is a code address that must be relocated
    /// (`do_call` / `do_jump` / `do_switch` in sc6.c resolve it from the label
    /// table). Note that [`Opcode::Casetbl`]'s trailing table also holds code
    /// addresses; see [`Operands::CaseTable`].
    pub fn is_jump(self) -> bool {
        match self {
            Opcode::None => false,
            Opcode::LoadPri => false,
            Opcode::LoadAlt => false,
            Opcode::LoadSPri => false,
            Opcode::LoadSAlt => false,
            Opcode::LrefPri => false,
            Opcode::LrefAlt => false,
            Opcode::LrefSPri => false,
            Opcode::LrefSAlt => false,
            Opcode::LoadI => false,
            Opcode::LodbI => false,
            Opcode::ConstPri => false,
            Opcode::ConstAlt => false,
            Opcode::AddrPri => false,
            Opcode::AddrAlt => false,
            Opcode::StorPri => false,
            Opcode::StorAlt => false,
            Opcode::StorSPri => false,
            Opcode::StorSAlt => false,
            Opcode::SrefPri => false,
            Opcode::SrefAlt => false,
            Opcode::SrefSPri => false,
            Opcode::SrefSAlt => false,
            Opcode::StorI => false,
            Opcode::StrbI => false,
            Opcode::Lidx => false,
            Opcode::LidxB => false,
            Opcode::Idxaddr => false,
            Opcode::IdxaddrB => false,
            Opcode::AlignPri => false,
            Opcode::AlignAlt => false,
            Opcode::Lctrl => false,
            Opcode::Sctrl => false,
            Opcode::MovePri => false,
            Opcode::MoveAlt => false,
            Opcode::Xchg => false,
            Opcode::PushPri => false,
            Opcode::PushAlt => false,
            Opcode::PushR => false,
            Opcode::PushC => false,
            Opcode::Push => false,
            Opcode::PushS => false,
            Opcode::PopPri => false,
            Opcode::PopAlt => false,
            Opcode::Stack => false,
            Opcode::Heap => false,
            Opcode::Proc => false,
            Opcode::Ret => false,
            Opcode::Retn => false,
            Opcode::Call => true,
            Opcode::CallPri => false,
            Opcode::Jump => true,
            Opcode::Jrel => false,
            Opcode::Jzer => true,
            Opcode::Jnz => true,
            Opcode::Jeq => true,
            Opcode::Jneq => true,
            Opcode::Jless => true,
            Opcode::Jleq => true,
            Opcode::Jgrtr => true,
            Opcode::Jgeq => true,
            Opcode::Jsless => true,
            Opcode::Jsleq => true,
            Opcode::Jsgrtr => true,
            Opcode::Jsgeq => true,
            Opcode::Shl => false,
            Opcode::Shr => false,
            Opcode::Sshr => false,
            Opcode::ShlCPri => false,
            Opcode::ShlCAlt => false,
            Opcode::ShrCPri => false,
            Opcode::ShrCAlt => false,
            Opcode::Smul => false,
            Opcode::Sdiv => false,
            Opcode::SdivAlt => false,
            Opcode::Umul => false,
            Opcode::Udiv => false,
            Opcode::UdivAlt => false,
            Opcode::Add => false,
            Opcode::Sub => false,
            Opcode::SubAlt => false,
            Opcode::And => false,
            Opcode::Or => false,
            Opcode::Xor => false,
            Opcode::Not => false,
            Opcode::Neg => false,
            Opcode::Invert => false,
            Opcode::AddC => false,
            Opcode::SmulC => false,
            Opcode::ZeroPri => false,
            Opcode::ZeroAlt => false,
            Opcode::Zero => false,
            Opcode::ZeroS => false,
            Opcode::SignPri => false,
            Opcode::SignAlt => false,
            Opcode::Eq => false,
            Opcode::Neq => false,
            Opcode::Less => false,
            Opcode::Leq => false,
            Opcode::Grtr => false,
            Opcode::Geq => false,
            Opcode::Sless => false,
            Opcode::Sleq => false,
            Opcode::Sgrtr => false,
            Opcode::Sgeq => false,
            Opcode::EqCPri => false,
            Opcode::EqCAlt => false,
            Opcode::IncPri => false,
            Opcode::IncAlt => false,
            Opcode::Inc => false,
            Opcode::IncS => false,
            Opcode::IncI => false,
            Opcode::DecPri => false,
            Opcode::DecAlt => false,
            Opcode::Dec => false,
            Opcode::DecS => false,
            Opcode::DecI => false,
            Opcode::Movs => false,
            Opcode::Cmps => false,
            Opcode::Fill => false,
            Opcode::Halt => false,
            Opcode::Bounds => false,
            Opcode::SysreqPri => false,
            Opcode::SysreqC => false,
            Opcode::File => false,
            Opcode::Line => false,
            Opcode::Symbol => false,
            Opcode::Srange => false,
            Opcode::JumpPri => false,
            Opcode::Switch => true,
            Opcode::Casetbl => false,
            Opcode::SwapPri => false,
            Opcode::SwapAlt => false,
            Opcode::Pushaddr => false,
            Opcode::Nop => false,
            Opcode::SysreqD => false,
            Opcode::Symtag => false,
            Opcode::Break => false,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn discriminants_match_the_compiler_table() {
        // Spot checks against sc6.c's opcodelist[].
        assert_eq!(Opcode::None as u8, 0);
        assert_eq!(Opcode::LoadPri as u8, 1);
        assert_eq!(Opcode::ConstPri as u8, 11);
        assert_eq!(Opcode::Proc as u8, 46);
        assert_eq!(Opcode::Call as u8, 49);
        assert_eq!(Opcode::Retn as u8, 48);
        assert_eq!(Opcode::Jump as u8, 51);
        assert_eq!(Opcode::Add as u8, 78);
        assert_eq!(Opcode::Halt as u8, 120);
        assert_eq!(Opcode::SysreqC as u8, 123);
        assert_eq!(Opcode::Switch as u8, 129);
        assert_eq!(Opcode::Casetbl as u8, 130);
        assert_eq!(Opcode::Nop as u8, 134);
        assert_eq!(Opcode::Break as u8, 137);
    }

    #[test]
    fn table_is_dense_and_ordered() {
        for (i, op) in ALL.iter().enumerate() {
            assert_eq!(op.raw() as usize, i, "hole at opcode {i}");
            assert_eq!(Opcode::from_raw(op.raw()), Some(*op));
        }
        assert_eq!(Opcode::from_raw(ALL.len() as u8), Option::None);
    }

    #[test]
    fn mnemonics_round_trip() {
        for op in ALL {
            assert_eq!(Opcode::from_mnemonic(op.mnemonic()), Some(op), "{:?}", op);
        }
        assert_eq!(Opcode::from_mnemonic("not.an.opcode"), Option::None);
        // spelling matches sc6.c, dots and all
        assert_eq!(Opcode::LoadSPri.mnemonic(), "load.s.pri");
        assert_eq!(Opcode::SysreqC.mnemonic(), "sysreq.c");
        assert_eq!(Opcode::ShlCAlt.mnemonic(), "shl.c.alt");
    }

    #[test]
    fn mnemonics_are_unique() {
        let mut seen: Vec<&str> = ALL.iter().map(|o| o.mnemonic()).collect();
        seen.sort_unstable();
        let count = seen.len();
        seen.dedup();
        assert_eq!(seen.len(), count, "duplicate mnemonic");
    }

    #[test]
    fn arity_matches_sc6c() {
        // parm0 rows
        for op in [Opcode::LoadI, Opcode::PushPri, Opcode::Proc, Opcode::Retn, Opcode::Add, Opcode::JumpPri, Opcode::SysreqPri, Opcode::Nop, Opcode::Break] {
            assert_eq!(op.operands(), Operands::None, "{:?}", op);
            assert_eq!(op.operands().count(), Some(0));
        }
        // parm1 rows
        for op in [Opcode::LoadPri, Opcode::ConstAlt, Opcode::Stack, Opcode::Heap, Opcode::Push, Opcode::AddC, Opcode::Halt, Opcode::Bounds, Opcode::SysreqC, Opcode::Pushaddr, Opcode::Jrel] {
            assert_eq!(op.operands(), Operands::One, "{:?}", op);
        }
        // do_call / do_jump / do_switch: one operand, a code address
        for op in [Opcode::Call, Opcode::Jump, Opcode::Jzer, Opcode::Jsgeq, Opcode::Switch] {
            assert_eq!(op.operands(), Operands::One, "{:?}", op);
            assert!(op.is_jump(), "{:?}", op);
        }
        // parm2 debug rows
        assert_eq!(Opcode::Line.operands(), Operands::Two);
        assert_eq!(Opcode::Srange.operands(), Operands::Two);
        // variable-length rows
        assert_eq!(Opcode::File.operands(), Operands::Variable);
        assert_eq!(Opcode::Symbol.operands(), Operands::Variable);
        assert_eq!(Opcode::File.operands().count(), Option::None);
        // the case table
        assert_eq!(Opcode::Casetbl.operands(), Operands::CaseTable);
        assert_eq!(Opcode::Casetbl.operands().count(), Option::None);
    }

    #[test]
    fn only_label_resolved_operands_are_jumps() {
        // jrel takes a plain number, not a label (sc6.c: parm1, /* always a number */)
        assert!(!Opcode::Jrel.is_jump());
        // jump.pri and call.pri take their target in a register
        assert!(!Opcode::JumpPri.is_jump());
        assert!(!Opcode::CallPri.is_jump());
        // casetbl's addresses live in the trailing table, not in an operand
        assert!(!Opcode::Casetbl.is_jump());
        assert_eq!(ALL.iter().filter(|o| o.is_jump()).count(), 15);
        // every jump carries exactly one operand cell
        for op in ALL.iter().filter(|o| o.is_jump()) {
            assert_eq!(op.operands(), Operands::One, "{:?}", op);
        }
    }
}
