[package]
name = "zpc-parse"
description = "Parser producing the zpc AST"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
zpc-diag.workspace = true
zpc-lex.workspace = true
zpc-ast.workspace = true
