[package]
name = "zpc"
description = "Driver tying the zpc Pawn compiler phases together"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
zpc-diag.workspace = true
zpc-lex.workspace = true
zpc-ast.workspace = true
zpc-parse.workspace = true
zpc-sema.workspace = true
zpc-codegen.workspace = true
zpc-asm.workspace = true
zpc-amxx.workspace = true
