// Parse the compiler's assembler opcode table -> crates/zpc-asm/src/opcode.rs
//
// Source of truth: libpc300/sc6.c `opcodelist[]`, which pairs each mnemonic with
// its numeric opcode and the emit function that defines the operand encoding.
//
// NOTE: the libpc300 copy of amx.h in this tree does NOT contain the `OP_*` enum
// (it only declares the AMX runtime structs), so sc6.c is the authoritative
// numbering available. sc6.c comments out the debug-only opcodes it never emits;
// those are supplied by GAPS below so the table is dense over 0..=137.
//
// usage: node scripts/genopcodes.mjs <path/to/sc6.c> <out.rs>
import fs from 'node:fs';

const SRC = process.argv[2];
const OUT = process.argv[3];

// Opcodes present in the AMX instruction space but commented out of sc6.c's
// opcodelist (debug records that AMX Mod X never emits). Mnemonic + emit
// function are taken from the commented-out sc6.c lines themselves:
//   /*{124, "file",   sIN_CSEG, do_file }, */
//   /*{125, "line",   sIN_CSEG, parm2 }, */
//   /*{126, "symbol", sIN_CSEG, do_symbol }, */
//   /*{127, "srange", sIN_CSEG, parm2 }, -- version 1 */
//   /*{136, "symtag", sIN_CSEG, parm1 },  -- version 7 */
// plus opcode 0, the "invalid instruction" node (`{0, NULL, 0, noop}`).
const GAPS = [
  [0, 'none', 'noop', 'Not an instruction. sc6.c reserves entry 0 of `opcodelist` as the\n/// "invalid instruction" node; the mnemonic `none` is our own placeholder so that\n/// every variant round-trips through [`Opcode::mnemonic`].'],
  [124, 'file', 'do_file', 'Debug record: source file name. Variable length (the string follows).\n/// Commented out of sc6.c\'s table - never emitted by this compiler.'],
  [125, 'line', 'parm2', 'Debug record: line number. Commented out of sc6.c\'s table.'],
  [126, 'symbol', 'do_symbol', 'Debug record: symbol name. Variable length. Commented out of sc6.c\'s table.'],
  [127, 'srange', 'parm2', 'Debug record: symbol range. Commented out of sc6.c\'s table.'],
  [136, 'symtag', 'parm1', 'Debug record: symbol tag. Commented out of sc6.c\'s table.'],
];

// Mnemonics whose single operand is a code address that the assembler resolves
// from the label table (`do_call` / `do_jump` / `do_switch` in sc6.c write
// `lbltab[i]`, i.e. a relocated code offset).
const CODE_ADDR_FNS = new Set(['do_call', 'do_jump', 'do_switch']);

// Human-readable notes for opcodes whose purpose is not obvious from the name.
const DOCS = {
  1: 'PRI = [address]', 2: 'ALT = [address]',
  3: 'PRI = [FRM + offset]', 4: 'ALT = [FRM + offset]',
  5: 'PRI = [[address]]', 6: 'ALT = [[address]]',
  7: 'PRI = [[FRM + offset]]', 8: 'ALT = [[FRM + offset]]',
  9: 'PRI = [PRI]', 10: 'PRI = "number" bytes from [PRI] (partial cell load)',
  11: 'PRI = value', 12: 'ALT = value',
  13: 'PRI = FRM + offset', 14: 'ALT = FRM + offset',
  15: '[address] = PRI', 16: '[address] = ALT',
  23: '[ALT] = PRI', 24: 'store "number" bytes of PRI at [ALT]',
  25: 'PRI = [ALT + (PRI x cell size)]', 26: 'PRI = [ALT + (PRI << shift)]',
  27: 'PRI = ALT + (PRI x cell size)', 28: 'PRI = ALT + (PRI << shift)',
  29: 'align PRI for a packed-string access of "number" bytes',
  31: 'PRI = special register (COD/DAT/HEA/STP/STK/FRM/CIP)',
  32: 'special register = PRI',
  38: 'push a reference: the value at [value] relative to DAT, "value" times',
  44: 'ALT = STK, STK = STK + value (adjust the stack)',
  45: 'ALT = HEA, HEA = HEA + value (allocate on the heap)',
  46: 'function prologue: push FRM, FRM = STK',
  47: 'function epilogue without stack cleanup', 48: 'function epilogue: pop FRM and the argument count',
  49: 'call a function; the operand is a code address',
  51: 'unconditional jump; the operand is a code address',
  52: 'jump relative to the current CIP by a plain number (not a label)',
  120: 'abort execution with the given exit code',
  121: 'abort with an array-bounds error if PRI > value',
  122: 'call the native function whose index is in PRI',
  123: 'call the native function with the given index (arguments already pushed)',
  128: 'jump to the code address in PRI',
  129: 'switch: the operand is the code address of the following CASETBL',
  130: 'case table header; followed by a variable-length list of (value, address) pairs',
  133: 'push the address of a local (FRM + offset)',
  134: 'no operation (padding)',
  135: 'call a native by its direct address; not generated by this compiler',
  137: 'debugger breakpoint',
};

const src = fs.readFileSync(SRC, 'utf8');
const table = src.slice(src.indexOf('static OPCODE opcodelist[]'));
const end = table.indexOf('};');

const rows = [];
for (const line of table.slice(0, end).split('\n')) {
  // Only uncommented rows: { 78, "add", sIN_CSEG, parm0 },
  const m = /^\s*\{\s*(\d+),\s*"([^"]+)",\s*(\w+),\s*(\w+)\s*\}/.exec(line);
  if (!m) continue;
  const [, num, name, segment, fn] = m;
  // Pseudo-instructions (segment 0 / data segment directives) carry opcode 0 and
  // are assembler directives, not AMX instructions: code, data, stksize, dump, case.
  if (segment !== 'sIN_CSEG') continue;
  if (name === 'case') continue; // emits 2 operands with NO opcode; part of CASETBL
  rows.push({ num: Number(num), name, fn, doc: DOCS[Number(num)] });
}
for (const [num, name, fn, doc] of GAPS) rows.push({ num, name, fn, doc });
rows.sort((a, b) => a.num - b.num);

// Density check: a hole means we mis-parsed and would emit a corrupt table.
rows.forEach((r, i) => {
  if (r.num !== i) throw new Error(`opcode table not dense at ${i}: got ${r.num} (${r.name})`);
});

// "load.s.pri" -> "LoadSPri"
const variant = (n) => n.split('.').map((p) => p[0].toUpperCase() + p.slice(1)).join('');

const operands = (r) => {
  if (r.fn === 'parm0' || r.fn === 'noop') return 'None';
  if (r.fn === 'parm1' || CODE_ADDR_FNS.has(r.fn)) return 'One';
  if (r.fn === 'parm2') return 'Two';
  if (r.fn === 'do_file' || r.fn === 'do_symbol') return 'Variable';
  throw new Error(`unknown emit function ${r.fn}`);
};

const rowsOut = rows.map((r) => ({
  ...r,
  variant: variant(r.name),
  operands: r.name === 'casetbl' ? 'CaseTable' : operands(r),
  jump: CODE_ADDR_FNS.has(r.fn),
}));

const q = (s) => JSON.stringify(s);
const decl = rowsOut.map((r) => {
  const doc = r.doc ? `    /// ${r.doc.replace(/\n/g, '\n    ')}\n` : '';
  return `${doc}    ${r.variant} = ${r.num},`;
}).join('\n');

const arm = (f) => rowsOut.map((r) => `            Opcode::${r.variant} => ${f(r)},`).join('\n');

const out = `//! The AMX instruction set: opcode numbers, mnemonics and operand encoding.
//!
//! GENERATED by \`scripts/genopcodes.mjs\` from the AMX Mod X compiler's
//! \`libpc300/sc6.c\` \`opcodelist[]\` table - do not edit by hand.
//!
//! The numbers here are a binary format: the assembler writes them straight into
//! the \`.amx\` code segment, so a wrong value produces a plugin that misbehaves at
//! runtime rather than failing to compile. \`sc6.c\` is the authoritative source in
//! this tree; the copy of \`amx.h\` shipped with \`libpc300\` declares only the runtime
//! structures and does not contain the \`OP_*\` enum.
//!
//! Operand counts come from the emit function each row is bound to in \`sc6.c\`:
//! \`parm0\` writes the opcode alone, \`parm1\` writes one operand cell, \`parm2\` two,
//! and \`do_call\` / \`do_jump\` / \`do_switch\` each write one operand cell holding a
//! resolved code address (\`lbltab[i]\`). \`casetbl\` is declared \`parm0\` but is
//! followed by a variable-length table written by \`do_case\` - see [\`Operands\`].

/// How many cell-sized operands follow an opcode in the code segment.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Operands {
    /// No operands: the instruction is a single cell (sc6.c \`parm0\`).
    None,
    /// One operand cell (sc6.c \`parm1\`, \`do_call\`, \`do_jump\`, \`do_switch\`).
    One,
    /// Two operand cells (sc6.c \`parm2\`; debug records only).
    Two,
    /// [\`Opcode::Casetbl\`]: the opcode is followed by \`2 + 2 * n\` cells. sc6.c emits
    /// these as \`case\` rows through \`do_case\`, which writes two cells and *no*
    /// opcode. The first pair is \`(n, default_address)\`, the remaining \`n\` pairs are
    /// \`(match_value, code_address)\`. Every address in the table needs relocation.
    CaseTable,
    /// Variable length, encoded by the instruction itself (sc6.c \`do_file\` /
    /// \`do_symbol\`: a size cell followed by an inline string). Never emitted by
    /// this compiler - both rows are commented out of \`opcodelist\`.
    Variable,
}

impl Operands {
    /// The number of operand cells, when it is fixed. \`None\` for the
    /// variable-length forms, whose size can only be known from the bytecode.
    pub fn count(self) -> Option<u32> {
        match self {
            Operands::None => Some(0),
            Operands::One => Some(1),
            Operands::Two => Some(2),
            Operands::CaseTable | Operands::Variable => Option::None,
        }
    }
}

/// An AMX instruction. Discriminants are the on-disk opcode numbers.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[repr(u8)]
pub enum Opcode {
${decl}
}

/// Every opcode, in ascending numeric order.
pub const ALL: [Opcode; ${rowsOut.length}] = [
${rowsOut.map((r) => `    Opcode::${r.variant},`).join('\n')}
];

impl Opcode {
    /// The mnemonic as \`sc6.c\`'s \`opcodelist[]\` spells it.
    pub fn mnemonic(self) -> &'static str {
        match self {
${arm((r) => q(r.name))}
        }
    }

    /// Look up an opcode by mnemonic. Case-sensitive: the compiler emits
    /// lower-case mnemonics, and \`sc6.c\`'s \`findopcode\` binary-searches this exact
    /// spelling.
    pub fn from_mnemonic(name: &str) -> Option<Opcode> {
        Some(match name {
${rowsOut.map((r) => `            ${q(r.name)} => Opcode::${r.variant},`).join('\n')}
            _ => return Option::None,
        })
    }

    /// The opcode's numeric value, as written to the code segment.
    pub fn raw(self) -> u8 {
        self as u8
    }

    /// Decode a numeric opcode read back from bytecode.
    pub fn from_raw(raw: u8) -> Option<Opcode> {
        ALL.get(raw as usize).copied()
    }

    /// How many operand cells follow this opcode.
    pub fn operands(self) -> Operands {
        match self {
${arm((r) => `Operands::${r.operands}`)}
        }
    }

    /// True when the single operand is a code address that must be relocated
    /// (\`do_call\` / \`do_jump\` / \`do_switch\` in sc6.c resolve it from the label
    /// table). Note that [\`Opcode::Casetbl\`]'s trailing table also holds code
    /// addresses; see [\`Operands::CaseTable\`].
    pub fn is_jump(self) -> bool {
        match self {
${arm((r) => (r.jump ? 'true' : 'false'))}
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn discriminants_match_the_compiler_table() {
        // Spot checks against sc6.c's opcodelist[].
        assert_eq!(Opcode::None as u8, 0);
        assert_eq!(Opcode::LoadPri as u8, 1);
        assert_eq!(Opcode::ConstPri as u8, 11);
        assert_eq!(Opcode::Proc as u8, 46);
        assert_eq!(Opcode::Call as u8, 49);
        assert_eq!(Opcode::Retn as u8, 48);
        assert_eq!(Opcode::Jump as u8, 51);
        assert_eq!(Opcode::Add as u8, 78);
        assert_eq!(Opcode::Halt as u8, 120);
        assert_eq!(Opcode::SysreqC as u8, 123);
        assert_eq!(Opcode::Switch as u8, 129);
        assert_eq!(Opcode::Casetbl as u8, 130);
        assert_eq!(Opcode::Nop as u8, 134);
        assert_eq!(Opcode::Break as u8, 137);
    }

    #[test]
    fn table_is_dense_and_ordered() {
        for (i, op) in ALL.iter().enumerate() {
            assert_eq!(op.raw() as usize, i, "hole at opcode {i}");
            assert_eq!(Opcode::from_raw(op.raw()), Some(*op));
        }
        assert_eq!(Opcode::from_raw(ALL.len() as u8), Option::None);
    }

    #[test]
    fn mnemonics_round_trip() {
        for op in ALL {
            assert_eq!(Opcode::from_mnemonic(op.mnemonic()), Some(op), "{:?}", op);
        }
        assert_eq!(Opcode::from_mnemonic("not.an.opcode"), Option::None);
        // spelling matches sc6.c, dots and all
        assert_eq!(Opcode::LoadSPri.mnemonic(), "load.s.pri");
        assert_eq!(Opcode::SysreqC.mnemonic(), "sysreq.c");
        assert_eq!(Opcode::ShlCAlt.mnemonic(), "shl.c.alt");
    }

    #[test]
    fn mnemonics_are_unique() {
        let mut seen: Vec<&str> = ALL.iter().map(|o| o.mnemonic()).collect();
        seen.sort_unstable();
        let count = seen.len();
        seen.dedup();
        assert_eq!(seen.len(), count, "duplicate mnemonic");
    }

    #[test]
    fn arity_matches_sc6c() {
        // parm0 rows
        for op in [Opcode::LoadI, Opcode::PushPri, Opcode::Proc, Opcode::Retn, Opcode::Add, Opcode::JumpPri, Opcode::SysreqPri, Opcode::Nop, Opcode::Break] {
            assert_eq!(op.operands(), Operands::None, "{:?}", op);
            assert_eq!(op.operands().count(), Some(0));
        }
        // parm1 rows
        for op in [Opcode::LoadPri, Opcode::ConstAlt, Opcode::Stack, Opcode::Heap, Opcode::Push, Opcode::AddC, Opcode::Halt, Opcode::Bounds, Opcode::SysreqC, Opcode::Pushaddr, Opcode::Jrel] {
            assert_eq!(op.operands(), Operands::One, "{:?}", op);
        }
        // do_call / do_jump / do_switch: one operand, a code address
        for op in [Opcode::Call, Opcode::Jump, Opcode::Jzer, Opcode::Jsgeq, Opcode::Switch] {
            assert_eq!(op.operands(), Operands::One, "{:?}", op);
            assert!(op.is_jump(), "{:?}", op);
        }
        // parm2 debug rows
        assert_eq!(Opcode::Line.operands(), Operands::Two);
        assert_eq!(Opcode::Srange.operands(), Operands::Two);
        // variable-length rows
        assert_eq!(Opcode::File.operands(), Operands::Variable);
        assert_eq!(Opcode::Symbol.operands(), Operands::Variable);
        assert_eq!(Opcode::File.operands().count(), Option::None);
        // the case table
        assert_eq!(Opcode::Casetbl.operands(), Operands::CaseTable);
        assert_eq!(Opcode::Casetbl.operands().count(), Option::None);
    }

    #[test]
    fn only_label_resolved_operands_are_jumps() {
        // jrel takes a plain number, not a label (sc6.c: parm1, /* always a number */)
        assert!(!Opcode::Jrel.is_jump());
        // jump.pri and call.pri take their target in a register
        assert!(!Opcode::JumpPri.is_jump());
        assert!(!Opcode::CallPri.is_jump());
        // casetbl's addresses live in the trailing table, not in an operand
        assert!(!Opcode::Casetbl.is_jump());
        assert_eq!(ALL.iter().filter(|o| o.is_jump()).count(), ${rowsOut.filter((r) => r.jump).length});
        // every jump carries exactly one operand cell
        for op in ALL.iter().filter(|o| o.is_jump()) {
            assert_eq!(op.operands(), Operands::One, "{:?}", op);
        }
    }
}
`;

fs.writeFileSync(OUT, out);
console.log(`wrote ${rowsOut.length} opcodes to ${OUT}`);
