[package]
name = "zpc-codegen"
description = "AST to Pawn assembly code generation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
zpc-diag.workspace = true
zpc-asm.workspace = true
zpc-ast.workspace = true
zpc-sema.workspace = true

[dev-dependencies]
zpc-lex.workspace = true
zpc-parse.workspace = true
