[package]
name = "zpc-ast"
description = "AST node definitions for the zpc Pawn compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
zpc-diag.workspace = true
